# Use root/example as user/password credentials
version: "3.9"

services:

  mongo:
    image: mongo
    restart: always
    networks:
      - mongonet
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password0
      MONGO_INITDB_DATABASE: Academy
  
  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - mongonet
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password0
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - 8080:8081

networks:
  mongonet:
  appnet:

volumes:
  db-data:
  